version: "3"
services:
  app:
    image: kiregmachine/fibonacci-flask
    ports:
      - 5000:5000
    container_name: app
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower